function J = jacobianR(Q, H, LX, LA, LB, LC, LD)
halfpi = pi/2;
theta1=Q(1);
theta2=Q(3);
theta3=Q(4);
theta4=Q(5);
theta5=Q(6);
theta6=Q(8);
theta7=Q(9);
theta8=Q(10);
J=[
[                                                                                                                                                                                             LC*cos(halfpi + theta2)*cos(halfpi + theta5)*cos(theta3) - LB*cos(halfpi + theta2)*sin(theta3) - LC*cos(halfpi + theta2)*sin(halfpi + theta5)*sin(theta3),                                                                                                                                            - LB*sin(halfpi + theta2)*cos(theta3) - LC*cos(halfpi + theta5)*sin(halfpi + theta2)*sin(theta3) - LC*sin(halfpi + theta2)*sin(halfpi + theta5)*cos(theta3),                                                                                                                                            - LC*cos(halfpi + theta5)*sin(halfpi + theta2)*sin(theta3) - LC*sin(halfpi + theta2)*sin(halfpi + theta5)*cos(theta3),                                                                                                                               0,                                                                                                                                                                                          0]
[                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                                                                                                                                                                      LC*cos(halfpi + theta3 + theta5) - LB*sin(theta3),                                                                                                                                                                                                                                 LC*cos(halfpi + theta3 + theta5),                                                                                                                               0,                                                                                                                                                                                          0]
[                                                                                                                                                                                             LB*sin(halfpi + theta2)*sin(theta3) - LC*cos(halfpi + theta5)*sin(halfpi + theta2)*cos(theta3) + LC*sin(halfpi + theta2)*sin(halfpi + theta5)*sin(theta3),                                                                                                                                            - LB*cos(halfpi + theta2)*cos(theta3) - LC*cos(halfpi + theta2)*cos(halfpi + theta5)*sin(theta3) - LC*cos(halfpi + theta2)*sin(halfpi + theta5)*cos(theta3),                                                                                                                                            - LC*cos(halfpi + theta2)*cos(halfpi + theta5)*sin(theta3) - LC*cos(halfpi + theta2)*sin(halfpi + theta5)*cos(theta3),                                                                                                                               0,                                                                                                                                                                                          0]
[LD*sin(halfpi + theta2)*sin(theta6)*sin(theta7) - LB*cos(halfpi + theta2)*sin(theta3) + LC*cos(halfpi + theta2)*cos(halfpi + theta5)*cos(theta3) - LD*cos(halfpi + theta2)*sin(theta3 + theta5)*cos(theta7) - LC*cos(halfpi + theta2)*sin(halfpi + theta5)*sin(theta3) - LD*sin(halfpi + theta3 + theta5)*cos(halfpi + theta2)*cos(theta6)*sin(theta7), - LB*sin(halfpi + theta2)*cos(theta3) - LD*cos(theta3 + theta5)*sin(halfpi + theta2)*cos(theta7) - LC*cos(halfpi + theta5)*sin(halfpi + theta2)*sin(theta3) - LC*sin(halfpi + theta2)*sin(halfpi + theta5)*cos(theta3) - LD*cos(halfpi + theta3 + theta5)*sin(halfpi + theta2)*cos(theta6)*sin(theta7), - LD*cos(theta3 + theta5)*sin(halfpi + theta2)*cos(theta7) - LC*cos(halfpi + theta5)*sin(halfpi + theta2)*sin(theta3) - LC*sin(halfpi + theta2)*sin(halfpi + theta5)*cos(theta3) - LD*cos(halfpi + theta3 + theta5)*sin(halfpi + theta2)*cos(theta6)*sin(theta7), LD*sin(halfpi + theta3 + theta5)*sin(halfpi + theta2)*sin(theta6)*sin(theta7) - LD*cos(halfpi + theta2)*cos(theta6)*sin(theta7), LD*sin(halfpi + theta2)*sin(theta3 + theta5)*sin(theta7) - LD*cos(halfpi + theta2)*cos(theta7)*sin(theta6) - LD*sin(halfpi + theta3 + theta5)*sin(halfpi + theta2)*cos(theta6)*cos(theta7)]
[                                                                                                                                                                                                                                                                                                                                                     0,                                                                                                            LC*cos(halfpi + theta5)*cos(theta3) - LB*sin(theta3) - LD*sin(theta3 + theta5)*cos(theta7) - LC*sin(halfpi + theta5)*sin(theta3) - LD*sin(halfpi + theta3 + theta5)*cos(theta6)*sin(theta7),                                                                                       LC*cos(halfpi + theta5)*cos(theta3) - LD*sin(theta3 + theta5)*cos(theta7) - LC*sin(halfpi + theta5)*sin(theta3) - LD*sin(halfpi + theta3 + theta5)*cos(theta6)*sin(theta7),                                                                       -LD*cos(halfpi + theta3 + theta5)*sin(theta6)*sin(theta7),                                                                                             LD*cos(halfpi + theta3 + theta5)*cos(theta6)*cos(theta7) - LD*cos(theta3 + theta5)*sin(theta7)]
];
end

